
import { FieldHelper } from "../../shared/helper/field-helper";
import { ObjectHelper } from "../../shared/helper/object-helper";
import { Product } from "../data/product";

export class ProductHelper implements ObjectHelper<Product,String|null> {
        withAutoGeneratedId(): boolean { return true;  }
        getId(obj: Product): String | null { return obj.ref; };
        getIdKeyName(): string {return "ref"; }
        buildEmptyObject(): Product { return new Product(); };
        getEntityTypeName(): string { return "Product";  };
        essentialFieldNames(): string[] {return ["ref","label","price"]; }
        getFieldHelper(fieldName:string):FieldHelper|null{
                        switch(fieldName){
                                case "ref" : return new FieldHelper("code");
                                case "label" : return new FieldHelper("name");
                                case "price" : return new FieldHelper("price","number",0);
                                default : return null;//NB:FieldHelper(fieldName,fieldType,defaultValue)
                        }
                }
}